# shelly dimmer behind wall switch in the living room area
- platform: mqtt
  name: "kitchen ceiling lights"
  state_topic: "stat/kitchen-ceiling-lights/POWER1"
  command_topic: "cmnd/kitchen-ceiling-lights/EVENT"
  availability_topic: "tele/kitchen-ceiling-lights/LWT"
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
# shelly 1 behind wall switch in the master bedroom
# controls the ceiling lights
- platform: mqtt
  name: Master Bedroom Ceiling Lights
  state_topic: "shellies/shelly-mstrbedrm/relay/0"
  command_topic: "shellies/shelly-mstrbedrm/relay/0/command"
  payload_on: "on"
  payload_off: "off"
  icon: mdi:lamp
  qos: 1
  retain: false
# part of the sonoff R4 in the mudroom wall switch box
# this is connected to the 2nd switch from the right
- platform: mqtt
  name: "mudroom light"
  unique_id: sonoff4ch_1-sw2
  state_topic: "stat/mudroom-4ch/POWER2"
  command_topic: "cmnd/mudroom-4ch/POWER2"
  availability_topic: "tele/mudroom-4ch/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  icon: mdi:ceiling-light
# part of the sonoff R4 in the mudroom wall switch box
# this is connected to the first switch from the right
- platform: mqtt
  name: "garage light"
  unique_id: sonoff4ch_1-sw1
  state_topic: "stat/mudroom-4ch/POWER1"
  command_topic: "cmnd/mudroom-4ch/POWER1"
  availability_topic: "tele/mudroom-4ch/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  icon: mdi:home-lightbulb-outline

