
# Configure a default setup of Home Assistant (frontend, api, etc)

homeassistant:
  name: 130 Anna Marie Way
  latitude: 36.030099
  longitude: -78.528541
  elevation: 120
  unit_system: imperial
  time_zone: America/New_York
  packages: !include_dir_named packages
  allowlist_external_dirs:
    - /config/frigate/
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24


#     - type: legacy_api_password
#       api_password: !secret strongpw_1
  customize:
    climate.thermostat_75_A1_CA:
      friendly_name: Bonus Room Thermostat
# Text to speech
tts:
  - platform: google_translate
    language: en
    service_name: google_say
    base_url: http://192.168.1.184:8123

#apcupsd:
#  host: 127.0.0.1
#  port: 3551

frontend:
  themes: !include_dir_merge_named themes

input_boolean:
  dark_outside:
    name: Dark Outside
    icon: mdi:weather-sunset
  security_camera_notify:
    name: Security Camera Text Alert
    icon: mdi:camera-burst
  security_camera_voice_alert:
    name: Security Camera Voice Alert
    icon: mdi:camera-burst
  person_upstairs:
    name: Person Upstairs
    icon: mdi:human-male
  ws_defeat_sleep:
    name: "Disable sleep on WS"
  climate_heat_mode:
    name: "Enable thermostat heating mode"
    

#tplink:
#  switch:
#    - host: 192.168.1.25
    
switch:
  - platform: mqtt
    name: "Attic Light"
    state_topic: "stat/attic_lightsw_77245E/RESULT"
    value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/attic_lightsw_77245E/POWER"
    availability_topic: "tele/attic_lightsw_77245E/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    icon: mdi:lamp
  - platform: mqtt
    name: "backyard-lights"
    state_topic: "stat/backyard-lights/RESULT"
    value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/backyard-lights/POWER"
    availability_topic: "tele/backyard-lights/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
    icon: mdi:spotlight-beam
  - platform: mqtt
    name: "Landscape Lights"
    state_topic: "stat/landscape-lights/RESULT"
    value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/landscape-lights/POWER"
    availability_topic: "tele/landscape-lights/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
    icon: mdi:spotlight-beam    
  - platform: mqtt
    name: "Crawlspace Light"
    state_topic: "stat/crawlspace-light/RESULT"
    value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/crawlspace-light/POWER"
    availability_topic: "tele/crawlspace-light/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    icon: mdi:lamp
  - platform: mqtt
    name: "kitchen ceiling lights"
    state_topic: "stat/kitchen-ceiling-lights/POWER1"
    command_topic: "cmnd/kitchen-ceiling-lights/EVENT"
    availability_topic: "tele/kitchen-ceiling-lights/LWT"
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    
lock:
  - platform: mqtt
    name: Crawlspace Door
    state_topic: "shellies/shelly1-772440/relay/0"
    command_topic: "shellies/shelly1-772440/relay/0/command"
    payload_lock: "on"
    payload_unlock: "off"
    state_locked: "on"
    state_unlocked: "off"
    optimistic: false
    qos: 1
    retain: true

light:
  - platform: mqtt
    schema: template
    name:  kitchen counter lights
    state_topic: "shellies/shellydimmer-F36B29/light/0/status"
    state_template: '{% if value_json.ison %} on {% else %} off {% endif %}'
    command_topic: "shellies/shellydimmer-F36B29/light/0/set"
    command_on_template: '{"turn": "on"{% if brightness is defined %}, "brightness": {{(brightness | float * 0.3882 + 1) | round(0)}}{% endif %}}'
    command_off_template: '{"turn": "off"}'
    brightness_template: '{{ (value_json.brightness | float * 2.55) | round(0) }}'

# camera:
#  - platform: generic
#    name: Wyzecam
#    stream_source: rtsp://dennis:336647@192.168.1.65/live
#    still_image_url: http://127.0.0.1:8123/local/office.jpg

sonoff:
  username: dennis.taul@gmail.com
  password: 855karen

#  scan_interval: 60
#  grace_period: 600
#  api_region: 'us'
#  entity_prefix: True
#  debug: False

shell_command:
  mount_frigate_clips: mkdir -p /media/frigate/clips;mount -t cifs -o username=dennis,password=855karen,domain=WORKGROUP //dell-t7810.local/Media/frigate/clips /media/frigate/clips

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
