
# Configure a default setup of Home Assistant (frontend, api, etc)

homeassistant:
  name: 130 Anna Marie Way
  latitude: 36.030099
  longitude: -78.528541
  elevation: 120
  unit_system: imperial
  time_zone: America/New_York
  packages: !include_dir_named packages
  allowlist_external_dirs:
    - /config/frigate/
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24


#     - type: legacy_api_password
#       api_password: !secret strongpw_1
  customize:
    climate.thermostat_75_A1_CA:
      friendly_name: Bonus Room Thermostat
# Text to speech
tts:
  - platform: google_translate
    language: en
    service_name: google_say
    base_url: http://192.168.1.184:8123

#apcupsd:
#  host: 127.0.0.1
#  port: 3551

frontend:
  themes: !include_dir_merge_named themes
    

#tplink:
#  switch:
#    - host: 192.168.1.25
    
    
lock:
  - platform: mqtt
    name: Crawlspace Door
    state_topic: "shellies/shelly1-772440/relay/0"
    command_topic: "shellies/shelly1-772440/relay/0/command"
    payload_lock: "on"
    payload_unlock: "off"
    state_locked: "on"
    state_unlocked: "off"
    optimistic: false
    qos: 1
    retain: true

light:
  - platform: mqtt
    schema: template
    name:  kitchen counter lights
    state_topic: "shellies/shellydimmer-F36B29/light/0/status"
    state_template: '{% if value_json.ison %} on {% else %} off {% endif %}'
    command_topic: "shellies/shellydimmer-F36B29/light/0/set"
    command_on_template: '{"turn": "on"{% if brightness is defined %}, "brightness": {{(brightness | float * 0.3882 + 1) | round(0)}}{% endif %}}'
    command_off_template: '{"turn": "off"}'
    brightness_template: '{{ (value_json.brightness | float * 2.55) | round(0) }}'

# camera:
#  - platform: generic
#    name: Wyzecam
#    stream_source: rtsp://dennis:336647@192.168.1.65/live
#    still_image_url: http://127.0.0.1:8123/local/office.jpg

sonoff:
  username: dennis.taul@gmail.com
  password: 855karen

#  scan_interval: 60
#  grace_period: 600
#  api_region: 'us'
#  entity_prefix: True
#  debug: False

shell_command:
  mount_frigate_clips: mkdir -p /media/frigate/clips;mount -t cifs -o username=dennis,password=855karen,domain=WORKGROUP //dell-t7810.local/Media/frigate/clips /media/frigate/clips

group: !include groups.yaml
automation: !include automations.yaml
#script: !include scripts.yaml
script: !include_dir_named scripts/
scene: !include scenes.yaml

switch: !include_dir_merge_list switches
input_boolean: !include input_boolean.yaml