alias: "Handle doorbell button push"
trigger:
  - platform: state
    entity_id: binary_sensor.garage_doorbell
    from: 'off'
    to: 'on'
action:
  - service: script.announce_echo_chk_outside
    data:
      message: <audio src="soundbank://soundlibrary/home/amzn_sfx_doorbell_chime_02"/>
  - service: script.announce_echo_chk_outside
    data_template:
      message: "Someone is at the garage kitchen door"
mode: single
