alias: "Upstairs Bedrm WallSwitch"
mode: single
trigger:
  - platform: state
    entity_id: binary_sensor.upstairs_bedroom_wall_switch
condition:
  ##################
  # these are necessary due to random wifi interruption
  # resulting in transition through unknown state
  condition: and
  conditions:
    - condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.upstairs_bedroom_wall_switch
          state: "on"
        - condition: state
          entity_id: binary_sensor.upstairs_bedroom_wall_switch
          state: "off"
    - condition: template
      value_template: '{{ trigger.from_state.state != "unavailable" }}'
    - condition: template
      value_template: '{{ trigger.to_state.state != "unavailable" }}'
    - condition: template
      value_template: '{{ trigger.from_state.state != trigger.to_state.state }}'
    - condition: numeric_state
      entity_id: sensor.uptime_minutes
      above: 3
action:
  - service: switch.toggle
    entity_id: switch.sonoff_1000a3970d
  - service: system_log.write
    data_template:
      message: "upstbedrm lamp toggle triggered by switch going from state {{trigger.from_state.state}} to {{trigger.to_state.state}}"
      level: warning
  - delay: 1
