alias: "Publish Weather Data"
# the rain reading is force published every 60 sec so
# use it to trigger publishing to MQTT which in turn
# tickled weewx to collect all the readings into its database
trigger:
  - platform: state
    entity_id: sensor.ws_rain
condition:
  # Adding this condition due to observations where some of the reading
  # are marked as 'unknown' for a reason I could not determine, this
  # seems to do the job of making sure the reading values do not fall into
  # the default float values. The default float values caused weewx to screw
  # up its reports with the averaging calculations it does.
    - condition: template
      value_template: '{{ is_number(states.sensor.ws_temp.state) }}'
action:
  - service: mqtt.publish
    data_template:
      topic: 'pws/outTemp'
      payload: "{{ states('sensor.ws_temp')|float(0.0) }}"
  - service: mqtt.publish
    data_template:
        topic: 'pws/outHumidity'
        payload: "{{ states('sensor.ws_relative_humidity')|float(30) }}"
  - service: mqtt.publish
    data_template:
      topic: 'pws/rain'
      payload: "{{ states('sensor.ws_rain')|float(0.0) }}"
  - service: mqtt.publish
    data_template:
      topic: 'pws/windSpeed'
      payload: "{{ states('sensor.ws_wind')|float(0.0) }}"
  - service: mqtt.publish
    data_template:
      topic: 'pws/windDir'
      payload: "{{ states('sensor.ws_windDir')|int(245) }}"
  - service: mqtt.publish
    data_template:
      topic: 'pws/barometer'
      payload: "{{ states('sensor.ws_atmospheric_pressure')|float(29) }}"
  - service: mqtt.publish
    data_template:
      topic: 'pws/txBatteryStatus'
      payload: "{{ states('sensor.ws_battery_level')|float(11.0) }}"
