alias: perform dusk actions
trigger:
  platform: state
  entity_id: input_boolean.dark_outside
  to: 'on'
condition: []
action:
  - service: switch.turn_on
    target:
      entity_id: switch.landscape_lights
  - service: switch.turn_on
    target:
      entity_id: switch.backyard_lights
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.livingroom_awake
