alias: scheduled nightime shutdown
trigger:
  - platform: time
    at: "22:50:00"
condition: []
action:
  - service: switch.turn_off
    target:
      entity_id: switch.landscape_lights
  - service: switch.turn_off
    target:
      entity_id: switch.backyard_lights
