alias: stop door open timer
trigger:
  - platform: state
    entity_id:
      - binary_sensor.attic_monitor_door
      - binary_sensor.crawlspace_door
      - binary_sensor.garage_kitchen_door
      - binary_sensor.upstairs_door
      - binary_sensor.front_door
    to: 'off'
action:
  - service: script.update_doorsopen_list
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.attic_monitor_door
            state: 'off'
          - condition: state
            entity_id: binary_sensor.crawlspace_door
            state: 'off'
          - condition: state
            entity_id: binary_sensor.garage_kitchen_door
            state: 'off'
          - condition: state
            entity_id: binary_sensor.upstairs_door
            state: 'off'
          - condition: state
            entity_id: binary_sensor.front_door
            state: 'off'
        sequence:
          - service: timer.cancel
            target:
              entity_id: timer.dooropen
    default:
      - service: timer.start
        target:
          entity_id: timer.dooropen
        data:
          duration: "00:05:00"
