
timer:
  dooropen:
    duration: "00:10:00"
  coversopen:
    duration: "00:10:00"

automation:
  - alias: start door open timer
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.attic_monitor_door
          - binary_sensor.crawlspace_door
          - binary_sensor.garage_kitchen_door
          - binary_sensor.upstairs_door
          - binary_sensor.front_door
        to: 'on'
    action:
      - service: script.update_doorsopen_list
      - service: timer.start
        target:
          entity_id: timer.dooropen
        data:
          duration: "00:08:00"
  - alias: stop door open timer
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.attic_monitor_door
          - binary_sensor.crawlspace_door
          - binary_sensor.garage_kitchen_door
          - binary_sensor.upstairs_door
          - binary_sensor.front_door
        to: 'off'
    action:
      - service: script.update_doorsopen_list
      - service: timer.cancel
        target:
          entity_id: timer.dooropen
  - alias: handle door open timer
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.dooropen
    action:
      - service: timer.start
        target:
          entity_id: timer.dooropen
        data:
          duration: "00:05:00"
      - service: script.announce_echo_chk_outside
        data_template:
          message: The {{states('input_text.dooropen_list')}} has been left open

  - alias: start covers open timer
    mode: restart 
    trigger:
      - platform: state
        entity_id: group.outdoor_covers
        id: cover_open_event
        to: 'open'
    action:
      - service: timer.start
        target:
          entity_id: timer.coversopen
        data:
          duration: "00:15:00"

  - alias: handle covers open timer
    mode: restart 
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.coversopen
        id: timer_finished
      - platform: state
        entity_id: group.outdoor_covers
        id: cover_close_event
        to: 'closed'
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: timer_finished
              - condition: state
                entity_id: input_boolean.person_outside
                state: 'on'
            sequence:
              - service: timer.start
                target:
                  entity_id: timer.coversopen
          - conditions:
              - condition: trigger
                id: timer_finished
              - condition: template
                # person outside motion more than 20 minutes ago
                value_template: >-
                  {{ (as_timestamp(now())-as_timestamp(states.input_boolean.person_outside.last_updated)) > 20*60 }}
            sequence:
              - service: script.close_covers_wannounce
          - conditions:
              - condition: trigger
                id: cover_close_event
            sequence:
              - service: timer.cancel
                target:
                  entity_id: timer.coversopen
        default:
          - service: timer.start
            target:
              entity_id: timer.coversopen
