# this setup was done to control the sonoff fan controller
# once I started moving to the treatlife fan controllers I realized
# I don't need this input_select when the fan is defined correctly
# In the case of the treatlife controllers, I use tasmota and MQTT
# and thus I can bring up the fan object and select the fan speed
# Also, the alexa smart home interface is able to determine how to
# control the fan.
input_select:
  bonus_rm_fan:
    name: bonus rm fan speeds
    options:
      - 'off'
      - low
      - medium
      - high
    initial: 'off'

automation:
- id: bnrm_fan_off
  alias: turn off bonus room fan
  trigger:
    platform: state
    entity_id: input_select.bonus_rm_fan
    to: 'off'
  action:
    service: fan.turn_off
    data:
      entity_id: fan.sonoff_1000994ed7
- id: bnrm_fan_speed
  alias: set bonus room fan speed
  trigger:
    platform: state
    entity_id: input_select.bonus_rm_fan
  condition:
    condition: template
    value_template: "{{ states('input_select.bonus_rm_fan') != 'off' }}"
  action:
    service: fan.set_speed
    data_template:
      entity_id: fan.sonoff_1000994ed7
      speed: "{{ states('input_select.bonus_rm_fan') }}"