automation:
  - alias: squelch security voice announcements
    trigger:
      - platform: state
        entity_id: input_boolean.person_outside
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: time
          after: '06:30:00'
          before: '22:30:00'
        - condition: state
          entity_id: input_boolean.person_inside
          state: 'on'
        - condition: state
          entity_id: input_boolean.home_occupied
          state: 'on'
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.security_camera_voice_alert
  - alias: enable security voice announcements
    trigger:
      - platform: state
        entity_id: input_boolean.person_outside
        to: 'off'
        for:
          seconds: 30
    condition:
      condition: and
      conditions:
        - condition: time
          after: '06:30:00'
          before: '22:30:00'
        - condition: state
          entity_id: input_boolean.person_inside
          state: 'on'
        - condition: state
          entity_id: input_boolean.home_occupied
          state: 'on'
    action:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.security_camera_voice_alert
  - alias: handle entrance door intrusion
    trigger:
      - platform: state
        entity_id: group.entrance_doors
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.security_mode
        state: 'on'
    action:
      - service: script.text_notify
        data_template:
          title: "Home Assistant Alarm"
          message: >-
            {% set exdoors = states | selectattr('entity_id', 'in', state_attr('group.entrance_doors','entity_id'))| selectattr('state','eq','open')| map(attribute='name') | list %}
            {%- for entity_id in exdoors -%}
              {% if loop.first %} Detected opening of the {% elif loop.last %} and the {% endif %}
                {{ entity_id }}
            {%- endfor -%}.
            
          who: "dennis"

  - alias: enable nobody home security
    trigger:
      - platform: state
        entity_id: input_boolean.home_occupied
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
    action:
      - service: script.set_security_nobody_home
                
  - alias: disable nobody home security
    trigger:
      - platform: state
        entity_id: input_boolean.home_occupied
        to: 'on'
        id: 'arrive_home'
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: 'arrive_home'
            sequence:
              - service: input_boolean.turn_off
                target: 
                  entity_id: input_boolean.security_mode
        default: []

  - alias: handle security mode off
    trigger:
      - platform: state
        entity_id: input_boolean.security_mode
        to: 'off'
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.security_camera_notify
      - service: script.text_notify
        data:
          title: "Home Assistant State Change"
          message: "Security mode with text alerts now disabled"
          who: "dennis"
  - alias: handle security voice alerts off
    trigger:
      - platform: state
        entity_id: input_boolean.security_camera_voice_alert
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.security_camera_notify
        state: 'off'
    action:
      - service: switch.turn_off
        target:
          entity_id: group.security_camera_recordings
          
  - alias: handle security voice alerts on
    trigger:
      - platform: state
        entity_id: input_boolean.security_camera_voice_alert
        to: 'on'
    action:
      - service: switch.turn_on
        target:
          entity_id: group.security_camera_recordings
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.exdoor_closed_since
